# Generated by Django 4.2.6 on 2023-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_discountproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountproduct',
            name='original_price',
            field=models.FloatField(default=0),
        ),
    ]
