# Generated by Django 4.2.6 on 2023-11-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_discountproduct_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
